{% set name = "freva" %}
{% set version = "2406.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/freva-{{ version }}.tar.gz
  sha256: 0acb1796c29ab1cd3e7353603c5e635299a89cfd3c22a30e267bb62ceb6dae8a

build:
  entry_points:
    - freva = freva.cli:main
    - freva-databrowser = freva.cli.databrowser:main
    - freva-esgf = freva.cli.esgf:main
    - freva-history = freva.cli.history:main
    - freva-plugin = freva.cli.plugin:main
    - freva-user-data = freva.cli.user_data:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - appdirs
    - pip
    - python >=3.7
  run:
    - appdirs
    - dask-core
    - django
    - ffmpeg
    - gitpython
    - git
    - h5netcdf
    - humanize
    - lazy_import
    - metadata-inspector
    - mysqlclient
    - netcdf4
    - numpy
    - pandas
    - pandoc
    - pillow
    - pymysql
    - pypdf2 !=2.10.1
    - python >=3.7
    - requests
    - rich
    - toml
    - toolz
    - typing_extensions
    - xarray

test:
  imports:
    - evaluation_system
    - freva
  commands:
    - pip check
    - freva --help
    - freva-databrowser --help
    - freva-esgf --help
    - freva-history --help
    - freva-plugin --help
    - freva-user-data --help
  requires:
    - pip

about:
  home: https://pypi.org/project/freva/
  summary: Free Evaluation and Analysis Framework (Freva)
  dev_url: https://github.com/FREVA-CLINT/freva
  license: BSD-2-Clause
  license_file:
    - LICENSE.md

extra:
  recipe-maintainers:
    - antarcticrainforest
