{% set name = "freva" %}
{% set version = "2506.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/freva-{{ version }}.tar.gz
  sha256: 2001d6865b212bfdcf5b45ea649219ef2091fc79fbb5d5ddde9a0514f0e2f350

build:
  entry_points:
    - freva = freva.cli:main
    - freva-databrowser = freva.cli.databrowser:main
    - freva-esgf = freva.cli.esgf:main
    - freva-history = freva.cli.history:main
    - freva-plugin = freva.cli.plugin:main
    - freva-user-data = freva.cli.user_data:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - appdirs
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - appdirs
    - gitpython
    - dask-core
    - django
    - humanize
    - ffmpeg
    - git
    - h5netcdf
    - lazy_import
    - mysqlclient
    - metadata-inspector
    - netcdf4
    - numpy
    - pymysql
    - pandas
    - pillow
    - pypdf2 !=2.10.1
    - requests
    - rich
    - setuptools
    - toml
    - toolz
    - typing_extensions
    - xarray

test:
  imports:
    - evaluation_system
    - freva
  commands:
    - pip check
    - freva --help
    - freva-databrowser --help
    - freva-esgf --help
    - freva-history --help
    - freva-plugin --help
    - freva-user-data --help
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: Free Evaluation and Analysis Framework (Freva)
  home: https://github.com/FREVA-CLINT/freva
  license: BSD-2-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - antarcticrainforest
    - mo-dkrz
